spring:
  datasource:
    url: jdbc:h2:mem:maindb

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

  sql:
    init:
      mode: embedded
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true