spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
      authentication-database: admin
      username: root
      password: example

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.otus.hw.mongock.changelog
