services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/book_library
      - DATASOURCE_USERNAME=admin
      - DATASOURCE_PASSWORD=admin

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  postgres:
    image: "postgres:17"
    ports:
      - "15432:5432"
    networks:
      - app-network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=book_library

networks:
  app-network:
    driver: bridge